config/routes.rb
Rails.application.routes.draw do

  get 'users' => "admin#users"

  post 'add_to_cart' => 'cart#add_to_cart'

  get 'view_order' => 'cart#view_order'

  get 'checkout' => 'cart#checkout'

  get 'remove_from_cart' => 'cart#remove_from_cart'

  post 'order_complete' => 'cart#order_complete'

  post 'edit_line_item' => 'cart#edit_line_item'

  devise_for :users
  root 'storefront#all_items'

  get 'categorical' => 'storefront#items_by_category'

  get 'branding' => 'storefront#items_by_brand'

  resources :products

end

app/controllers/cart_controller.rb
class CartController < ApplicationController

	include CartHelper

	before_filter :authenticate_user!, :except => [:add_to_cart, :view_order, :edit_line_item, :remove_from_cart]

  def add_to_cart

  	product = Product.find(params[:product_id])
 			
 			if quantity_check?(product, params[:quantity].to_i)
 				return			 		
  		else
  			line_item = LineItem.create(product_id: params[:product_id], quantity: params[:quantity])
  	  	
  	  	line_item.line_item_total = line_item.quantity * line_item.product.price

  	  	if user_signed_in?
  	  		line_item.customer_key = current_user.id
  	  	else
  	  		line_item.customer_key = remote_ip
  	  	end
  	  		
  	  	line_item.save

		  	redirect_to view_order_path
  		end
  end

	def remove_from_cart
		LineItem.find(params[:id]).destroy
		redirect_to :back
	end

	def edit_line_item
		line_item = LineItem.find(params[:id])

		if quantity_check?(line_item.product, params[:quantity].to_i)
			return
		else
			line_item.update(quantity: params[:quantity].to_i)
			line_item.line_item_total = line_item.quantity * line_item.product.price
		  	line_item.save
			redirect_to view_order_path
		end

	end

  def view_order
  	if user_signed_in?
  		@line_items = LineItem.where(customer_key: current_user.id)
  	else
  		@line_items = LineItem.where(customer_key: remote_ip)
  	end
  end

  def checkout
  	line_items = LineItem.all
  	@order = Order.create(user_id: current_user.id)

  	@order.subtotal = 0

  	line_items.each do |line_item|
  		@order.subtotal += line_item.line_item_total
=begin
	this creates a hash, with the line_item product id as the key, and the
	quantity as the value
=end
	 		@order.order_items[line_item.product_id] = line_item.quantity
	  end

	  @order.sales_tax = @order.subtotal * 0.07
	  @order.grand_total = @order.subtotal + @order.sales_tax
	  @order.save
	
		line_items.each do |line_item|
			line_item.product.quantity -= line_item.quantity
			line_item.product.save
		end

		LineItem.destroy_all
	end

	def order_complete

		@order = Order.find(params[:order_id])
		@amount = (@order.grand_total.to_f.round(2) * 100).to_i

  customer = Stripe::Customer.create(
      :email => current_user.email,
      :card => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer => customer.id,
      :amount => @amount,
      :description => 'Rails Stripe customer',
      :currency => 'usd'
    )

    rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to charges_path

	end

end

app/helpers/cart_helper.rb
module CartHelper

	def quantity_check?(product, quantity)
  	if product.quantity < quantity
			redirect_to product, notice: "Sorry, we only have #{product.quantity} left in stock."
			return true
		elsif quantity  <= 0
			redirect_to product, notice: "Sorry, you have to enter a positive number."  			
			return true
		else
			return false
		end

	end

end

app/views/cart/add_to_cart.html.erb
<h1>Cart#add_to_cart</h1>
<p>Find me in app/views/cart/add_to_cart.html.erb</p>

app/views/cart/checkout.html.erb
<h2>Thank you for shopping!</h2>
<p>Here is your order:</p>

<% @order.order_items.each do |k, v| %>
	<ul>
		<li> <%= v %> <%= Product.find(k).name %></li>
	</ul>
<% end %>


<p>Subtotal: <%= number_to_currency @order.subtotal %></p>
<p>Sales Tax: <%= number_to_currency @order.sales_tax %></p>
<p>------------------</p>
<p>
	<strong>Order Total:  <%= number_to_currency @order.grand_total %> </strong>
</p>

<div>
	<%= form_tag order_complete_path do %>
		<article>
			<label class="amount">
				<span><%= number_to_currency @order.grand_total %></span>
			</label>
		</article>
		<div>
			<%= hidden_field_tag :order_id, @order.id %>
		</div>

		<script src="http://checkout.stripe.com/checkout.js"
		class="stripe-button"
		data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
		data-description="Order #<%= @order.id %>"
		data-amount="<%= (@order.grand_total.to_f.round(2) * 100) %>"></script>
	<% end %>
</div>

app/views/cart/order_complete.html.erb
<h2>Thank you for your order.</h2>

<h4>
	Order # <%=@order.id %> will be shipping to you as soon as possible.
</h4>

app/views/cart/view_order.html.erb
<div class="row">
	<div class="col-md-4">
		<h2 class= "text-center">My Cart</h2>

		<div class="well">
			<% if @line_items != [] %>
					<% @line_items.each_with_index do |line_item, index| %>
					<h4><%= line_item.product.name %></h4>
					<ul>
						<li><%= number_to_currency line_item.product.price %></li>
						<li id="li_qty_<%= index %>">Qty: <%= line_item.quantity %> </li>
						<li id="edit_qty_<%= index %>" class="invisible">
							<%= form_tag(edit_line_item_path) do %>
								<%= number_field_tag :quantity, line_item.quantity %>
								<%= hidden_field_tag :id, line_item.id %>
								<%= submit_tag "Edit", class: "btn btn-danger" %>
							<% end %>
						</li>
						<li>Subtotal: <%= number_to_currency line_item.line_item_total %></li>
					</ul>
					<p>
						<button class= "btn btn-warning" id="edit_btn_<%= index %>">Edit</button>
						<%= link_to "Remove from Cart", remove_from_cart_path(id: line_item.id), class: "btn btn-danger" %>
					</p>

					<script>
					$(document).ready(function(){
						$('#edit_btn_<%= index %>').click(function(){
							$('#li_qty_<%= index %>').addClass("invisible");
							$('#edit_qty_<%= index %>').removeClass("invisible");
						})
					})
					</script>
				<% end %>

				<% else %>
					<h3>Your cart is empty.</h3>
				<% end %>

		<div>
			<%= link_to "Proceed to Checkout?", checkout_path, class: "btn btn-success" %>
		</div>
	</div>
</div>
</div>