config/routes.rb
Rails.application.routes.draw do

  get 'users' => "admin#users"

  post 'add_to_cart' => 'cart#add_to_cart'

  get 'view_order' => 'cart#view_order'

  get 'checkout' => 'cart#checkout'

  get 'remove_from_cart' => 'cart#remove_from_cart'

  post 'order_complete' => 'cart#order_complete'

  post 'edit_line_item' => 'cart#edit_line_item'

  devise_for :users
  root 'storefront#all_items'

  get 'categorical' => 'storefront#items_by_category'

  get 'branding' => 'storefront#items_by_brand'

  resources :products

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyStore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
​
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
       		<li><%= link_to "Home", root_path%></li>

          <li class="dropdown">
          	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Choose Brand<span class="caret"></span></a>
          	<ul class="dropdown-menu">
          		<% @brands.each do |brand| %>
          		<li><%= link_to brand, branding_path(name: brand) %></li>
          		<% end %>
          	</ul>
          </li>
          <li class="dropdown">
          	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Choose Category<span class="caret"></span></a>
          	<ul class="dropdown-menu">
          		<% @categories.each do |cat| %>
          		<li><%= link_to cat.name, categorical_path(cat_id: cat.id) %></li>
          		<% end %>
          	</ul>
          </li>
        </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? && current_user.role == "admin" %>
              <li><%= link_to "User Admin", users_path %></li>

            <% end %>
          	<li><%= link_to view_order_path do %>
              <i class="fa fa-shopping-cart" aria-hidden="true"></i> View Cart
              <% end %> 
            </li>
       		 <% if user_signed_in? %>
            <li><%= link_to "Edit Profile", edit_user_registration_path %> 

            </li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            <% else %>
            	<li><%= link_to "Sign In", new_user_session_path %></li>
      		 <% end %>

          </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

<div class="container">
<%= yield %>
</div>
</body>
</html>